version: "3.8"
services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - "27017:27017"
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
